### ISSUE TITLE
No Orisa icon

### ISSUE THREAD

**Issue by danielmarquard** [critcola/discourse-overwatch-hero-icons#3]
We don't have an Orisa icon yet, but I've asked the designer of a copyright-enforced vector icon of her if they'd be willing to contribute to @255kb's Overwatch font and this plugin.

I've added placeholders for Orisa as well as Doomfist. https://github.com/critcola/discourse-overwatch-hero-icons/commit/3d8f7f4b9ce8c0e22b91407fd177b65cd3473b4d

**Comment by danielmarquard** [comment]
Orisa's icon is ready to be added to the Overwatch font.

https://github.com/255kb/overwatch-heroes-icon-font/issues/7

**Comment by 255kb** [comment]
Hi there, I added Orisa to the font, sorry for the delay. It's published in version 1.2.1

**Comment by danielmarquard** [comment]
Thanks, @255kb! I've updated my plugin with your font.
